apiVersion: v1
kind: Service
metadata:
  name: netodep-svc
  labels:
     app  : netodup-app
spec:
  selector:
    app: netodup-app
  ports:
    - name      : nginx-listen
      protocol  : TCP
      port      : 10080
      targetPort: 80
    - name      : multi-listens
      protocol  : TCP
      port      : 10888
      targetPort: 8880
