apiVersion: apps/v1
kind: Deployment
metadata:
  name: netodep-dup
  labels:
    app: netodup-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netodup-app
  template:
    metadata:
      labels:
        app: netodup-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: nginx-listen
      - name: multitool
        image: wbitt/network-multitool:latest
        env:
        - name: HTTP_PORT
          value: "8880"
        - name: HTTPS_PORT
          value: "18443"
        ports:
        - containerPort: 8880
          name: multi-listen
        - containerPort: 18443
          name: multi-listens
